// Code generated by goctl. DO NOT EDIT.
// Source: notification_api.proto

package server

import (
	"context"

	"github.com/igorariza/golang-api-gozero-grpc/notification/firebase/rpc/internal/logic"
	"github.com/igorariza/golang-api-gozero-grpc/notification/firebase/rpc/internal/svc"
	"github.com/igorariza/golang-api-gozero-grpc/notification/firebase/rpc/types/notifications/v1alpha1"
)

type NotificationAPIServiceServer struct {
	svcCtx *svc.ServiceContext
	v1alpha1.UnimplementedNotificationAPIServiceServer
}

func NewNotificationAPIServiceServer(svcCtx *svc.ServiceContext) *NotificationAPIServiceServer {
	return &NotificationAPIServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationAPIServiceServer) CreateNotification(ctx context.Context, in *v1alpha1.CreateNotificationRequest) (*v1alpha1.CreateNotificationResponse, error) {
	l := logic.NewCreateNotificationLogic(ctx, s.svcCtx)
	return l.CreateNotification(in)
}
