// Code generated by goctl. DO NOT EDIT!
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixFilesCacheKey = "cache:files:"

type filesModel interface {
	Insert(ctx context.Context, data *Files) error
	FindOne(ctx context.Context, id string) (*Files, error)
	Update(ctx context.Context, data *Files) error
	Delete(ctx context.Context, id string) error
}

type defaultFilesModel struct {
	conn *monc.Model
}

func newDefaultFilesModel(conn *monc.Model) *defaultFilesModel {
	return &defaultFilesModel{conn: conn}
}

func (m *defaultFilesModel) Insert(ctx context.Context, data *Files) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixFilesCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultFilesModel) FindOne(ctx context.Context, id string) (*Files, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Files
	key := prefixFilesCacheKey + data.ID.Hex()
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFilesModel) Update(ctx context.Context, data *Files) error {
	data.UpdateAt = time.Now()
	key := prefixFilesCacheKey + data.ID.Hex()
	_, err := m.conn.ReplaceOne(ctx, key, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultFilesModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixFilesCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
